import { z } from 'zod';

// ── Shared Zod Schemas ────────────────────────────────────────────

/**
 * AgentConfig — the core configuration for a trading agent.
 * Generated by Gemini from a user prompt OR assembled via the ReactFlow builder.
 * Validated with Zod on both frontend and backend.
 */
export const AgentConfigSchema = z.object({
  name: z.string().min(3).max(50),

  strategyType: z.enum([
    'TREND_FOLLOW',
    'MEAN_REVERT',
    'BREAKOUT',
    'MOMENTUM',
    'SWING',
    'CUSTOM',
  ]),

  asset: z.string().default('HBAR/USDC'),

  timeframe: z.enum(['1m', '5m', '15m', '1h', '4h', '1d']),

  indicators: z.object({
    movingAverage: z.object({
      type: z.enum(['SMA', 'EMA', 'WMA']),
      period: z.number().int().min(5).max(200),
    }).optional(),

    rsi: z.object({
      period: z.number().int().default(14),
      overbought: z.number().default(70),
      oversold: z.number().default(30),
    }).optional(),

    macd: z.object({
      fast: z.number().int().default(12),
      slow: z.number().int().default(26),
      signal: z.number().int().default(9),
    }).optional(),

    bollingerBands: z.object({
      period: z.number().int().default(20),
      stdDev: z.number().default(2),
    }).optional(),
  }),

  risk: z.object({
    maxPositionSizePct: z.number().min(1).max(20).default(10),
    stopLossPct: z.number().min(0.5).max(10).default(3),
    takeProfitPct: z.number().min(1).max(50).default(8),
  }),
});

export type AgentConfig = z.infer<typeof AgentConfigSchema>;

// ── Agent Decision (result of each AI cycle) ─────────────────────

export const AgentDecisionSchema = z.object({
  signal: z.enum(['BUY', 'SELL', 'HOLD']),
  confidence: z.number().min(0).max(100),
  reasoning: z.string(),
  price: z.number(),
  indicators: z.record(z.number()).optional(),
  agentId: z.string().uuid(),
  timestamp: z.string().datetime(),
});

export type AgentDecision = z.infer<typeof AgentDecisionSchema>;

// ── API Request/Response Types ────────────────────────────────────

export const BuildFromPromptRequestSchema = z.object({
  prompt: z.string().min(20).max(1000),
});

export const DeployAgentRequestSchema = z.object({
  config: AgentConfigSchema,
  configHash: z.string(),
  walletAddress: z.string(), // Hedera account ID (0.0.XXXXX)
});

export const ListOnMarketplaceRequestSchema = z.object({
  agentId: z.string().uuid(),
  priceHbar: z.number().positive(),
  description: z.string().max(500).optional(),
});

// ── Hedera Entity Types ───────────────────────────────────────────

export interface HederaDeployResult {
  agentId: string;
  hcsTopicId: string;       // e.g., "0.0.4823901"
  hfsConfigId: string;      // e.g., "0.0.9876"
  contractTxId?: string;    // HSCS registration tx hash
  hashscanUrl: string;
  hcs10TopicId?: string;
}

export interface HCSMessage {
  sequenceNumber: string;
  consensusTimestamp: string;
  decision: AgentDecision;
  hashscanUrl: string;
}

export interface MarketplaceListing {
  agentId: string;
  name: string;
  strategyType: string;
  serialNumber: number;
  priceHbar: number;
  ipfsCID?: string;
  hcsTopicId: string;
  hfsConfigId: string;
  performance?: {
    totalTrades: number;
    winRate: number;
    pnl30d: number;
    avgConfidence: number;
  };
}

// ── Utility: getCronPattern ───────────────────────────────────────

/**
 * Converts a timeframe string to a BullMQ cron pattern.
 * Used to schedule agent execution cycles in BullMQ.
 */
export function getCronPattern(timeframe: AgentConfig['timeframe']): string {
  const patterns: Record<AgentConfig['timeframe'], string> = {
    '1m':  '* * * * *',         // Every minute
    '5m':  '*/5 * * * *',       // Every 5 minutes
    '15m': '*/15 * * * *',      // Every 15 minutes
    '1h':  '0 * * * *',         // Every hour
    '4h':  '0 */4 * * *',       // Every 4 hours
    '1d':  '0 0 * * *',         // Every day at midnight UTC
  };
  return patterns[timeframe];
}
